modify

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,25 +7,40 @@ php:
 services:
   - docker
 
-# travis runtime environment from here or settings.
 env:
 
 
-# put your normal pre-testing installs here
-install:
-  - echo "***** install step *****"
-
-# put your normal testing scripts here
-script:
-  - echo '***** script step *****'
-
-
+# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
+# (OPTIONAL) Install apt addons
+# (OPTIONAL) Install cache components
+# before_install
+# install
+# before_script
+# script
+# (OPTIONAL) before_cache (for cleaning up cache)
+# after_success or after_failure
+# (OPTIONAL) before_deploy
+# (OPTIONAL) deploy
+# (OPTIONAL) after_deploy
+# after_script
 before_install:
-  - echo 'before_install'
+  - set -e
+  - echo $(date)
+
+# install:
+#
+# after_install:
+#
+# before_script:
+#
+# script:
+#
+# after_script:
+
 
 
 after_success:
-  - echo 'after_success'
+  - echo '***** after_success *****'
   - set -e
   - echo $(date)
   - if [[ $TRAVIS_BRANCH == "master" ]]; then
@@ -39,3 +54,14 @@ after_success:
     docker tag ${DOCKER_IMAGE}:latest ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
     docker push ${ECR_REPOSITORY_DOMAIN}/${DOCKER_IMAGE}:latest;
     fi
+
+after_failure:
+  - echo '***** after_failure *****'
+
+# before_deploy:
+
+# deploy:
+
+# after_deploy:
+
+# after_script:
